CREATE TABLE CUSTOMER (
    Customer_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Customer_Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Phone_Num VARCHAR(50),
    Hashed_Password VARCHAR(255) NOT NULL,
    Address TEXT NOT NULL
);

CREATE TABLE RESTAURANT (
    Restaurant_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Restaurant_Name VARCHAR(255) NOT NULL,
    Address TEXT NOT NULL,
    Description TEXT,
    Opening_Hours VARCHAR(100) NOT NULL,
    Avg_Rating DECIMAL(3, 2)
);

CREATE TABLE RIDER (
    Rider_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Rider_Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Hashed_Password VARCHAR(255) NOT NULL,
    Phone_Num VARCHAR(50),
    Vehicle_Plate VARCHAR(20),
    Vehicle_Type VARCHAR(50) NOT NULL,
    Avg_Rating DECIMAL(3, 2)
);

CREATE TABLE FOOD (
    Food_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Food_Name VARCHAR(255) NOT NULL
);

CREATE TABLE MENU (
    Menu_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Restaurant_ID INT UNSIGNED NOT NULL,
    Food_ID INT UNSIGNED NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (Restaurant_ID) REFERENCES RESTAURANT(Restaurant_ID) ON DELETE CASCADE,
    FOREIGN KEY (Food_ID) REFERENCES FOOD(Food_ID) ON DELETE CASCADE
);

CREATE TABLE PAYMENT_METHOD (
    Payment_Method_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Customer_ID INT UNSIGNED NOT NULL,
    PaymentMethod VARCHAR(100) NOT NULL,
    FOREIGN KEY (Customer_ID) REFERENCES CUSTOMER(Customer_ID) ON DELETE CASCADE
);

CREATE TABLE `ORDER` (
    Order_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Customer_ID INT UNSIGNED NOT NULL,
    Restaurant_ID INT UNSIGNED NOT NULL,
    Rider_ID INT UNSIGNED NOT NULL,
    Payment_Method_ID INT UNSIGNED NOT NULL,
    Timestamp DATETIME NOT NULL,
    Order_Status VARCHAR(15) NOT NULL DEFAULT 'preparing', -- Allowed values: 'preparing', 'in delivery', 'completed'
    Total_Food_Price DECIMAL(10, 2) NOT NULL,
    Delivery_Fee DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (Customer_ID) REFERENCES CUSTOMER(Customer_ID),
    FOREIGN KEY (Restaurant_ID) REFERENCES RESTAURANT(Restaurant_ID),
    FOREIGN KEY (Rider_ID) REFERENCES RIDER(Rider_ID) ON DELETE CASCADE,
    FOREIGN KEY (Payment_Method_ID) REFERENCES PAYMENT_METHOD(Payment_Method_ID) ON DELETE CASCADE
);

CREATE TABLE ORDER_ITEM (
    Order_Item_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Order_ID INT UNSIGNED NOT NULL,
    Menu_ID INT UNSIGNED NOT NULL,
    Quantity INT UNSIGNED NOT NULL,
    PRIMARY KEY (Order_Item_ID, Order_ID),
    FOREIGN KEY (Order_ID) REFERENCES `ORDER`(Order_ID) ON DELETE CASCADE,
    FOREIGN KEY (Menu_ID) REFERENCES MENU(Menu_ID) ON DELETE CASCADE
);

CREATE TABLE REVIEW (
    Review_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Order_ID INT UNSIGNED NOT NULL,
    Comments TEXT,
    Restaurant_Rating INT UNSIGNED NOT NULL,
    Rider_Rating INT UNSIGNED NOT NULL,
    Review_Timestamp DATETIME NOT NULL,
    PRIMARY KEY (Review_ID, Order_ID),
    FOREIGN KEY (Order_ID) REFERENCES `ORDER`(Order_ID) ON DELETE CASCADE
);