CREATE TABLE CUSTOMER (
    Customer_ID SERIAL PRIMARY KEY,
    Customer_Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Phone_Num VARCHAR(50),
    Hashed_Password VARCHAR(255) NOT NULL,
    Address TEXT NOT NULL
);

CREATE TABLE RESTAURANT (
    Restaurant_ID SERIAL PRIMARY KEY,
    Restaurant_Name VARCHAR(255) NOT NULL,
    Address TEXT NOT NULL,
    Description TEXT,
    Opening_Hours VARCHAR(100) NOT NULL,
    Avg_Rating DECIMAL(3, 2)
);

CREATE TABLE RIDER (
    Rider_ID SERIAL PRIMARY KEY,
    Rider_Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Hashed_Password VARCHAR(255) NOT NULL,
    Phone_Num VARCHAR(50),
    Vehicle_Plate VARCHAR(20),
    Vehicle_Type VARCHAR(50) NOT NULL,
    Avg_Rating DECIMAL(3, 2)
);

CREATE TABLE FOOD (
    Food_ID SERIAL PRIMARY KEY,
    Food_Name VARCHAR(255) NOT NULL
);

CREATE TABLE MENU (
    Menu_ID SERIAL PRIMARY KEY,
    Restaurant_ID INT NOT NULL,
    Food_ID INT NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (Restaurant_ID) REFERENCES RESTAURANT(Restaurant_ID) ON DELETE CASCADE,
    FOREIGN KEY (Food_ID) REFERENCES FOOD(Food_ID) ON DELETE CASCADE
);

CREATE TABLE PAYMENT_METHOD (
    Payment_Method_ID SERIAL PRIMARY KEY,
    Customer_ID INT NOT NULL,
    PaymentMethod VARCHAR(100) NOT NULL,
    FOREIGN KEY (Customer_ID) REFERENCES CUSTOMER(Customer_ID) ON DELETE CASCADE
);

CREATE TABLE ORDERS (
    Order_ID SERIAL PRIMARY KEY,
    Customer_ID INT NOT NULL,
    Restaurant_ID INT NOT NULL,
    Rider_ID INT NOT NULL,
    Payment_Method_ID INT NOT NULL,
    Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Order_Status VARCHAR(15) NOT NULL DEFAULT 'preparing' CHECK (Order_Status IN ('preparing', 'in delivery', 'completed')), -- Fixed extra comma here
    Total_Food_Price DECIMAL(10, 2) NOT NULL,
    Delivery_Fee DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (Customer_ID) REFERENCES CUSTOMER(Customer_ID) ON DELETE RESTRICT,
    FOREIGN KEY (Restaurant_ID) REFERENCES RESTAURANT(Restaurant_ID) ON DELETE RESTRICT,
    FOREIGN KEY (Rider_ID) REFERENCES RIDER(Rider_ID) ON DELETE RESTRICT,
    FOREIGN KEY (Payment_Method_ID) REFERENCES PAYMENT_METHOD(Payment_Method_ID) ON DELETE RESTRICT
);

CREATE TABLE ORDER_ITEM (
    Order_Item_ID SERIAL PRIMARY KEY,
    Order_ID INT NOT NULL,
    Menu_ID INT NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID) ON DELETE CASCADE,
    FOREIGN KEY (Menu_ID) REFERENCES MENU(Menu_ID) ON DELETE CASCADE
);

CREATE TABLE REVIEW (
    Review_ID SERIAL PRIMARY KEY,
    Order_ID INT NOT NULL,
    Comments TEXT,
    Restaurant_Rating INT NOT NULL CHECK (Restaurant_Rating BETWEEN 1 AND 5),
    Rider_Rating INT NOT NULL CHECK (Rider_Rating BETWEEN 1 AND 5),
    Review_Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Order_ID) REFERENCES ORDERS(Order_ID) ON DELETE RESTRICT
);